標準エラーに出力

diff --git a/.github/workflows/image-release manual.yml b/.github/workflows/image-release manual.yml
--- a/.github/workflows/image-release manual.yml
+++ b/.github/workflows/image-release manual.yml
@@ -49,7 +49,7 @@ jobs:
         if echo "${TEST_VERSION}" | grep -E "^test\.[1-9][0-9]*$"; then
           echo "Valid test version"
         else
-          echo "Invalid test version"
+          echo "Invalid test version" >&2
           exit 1
         fi
 
@@ -60,7 +60,7 @@ jobs:
         if echo "${RELEASE_VERSION}" | grep -E "^4\.[0-9]+\.[0-9]+$"; then
           echo "Valid release version"
         else
-          echo "Invalid release version"
+          echo "Invalid release version" >&2
           exit 1
         fi
 
