異常終了ステータス追加

diff --git a/.github/workflows/image-release.yml b/.github/workflows/image-release.yml
--- a/.github/workflows/image-release.yml
+++ b/.github/workflows/image-release.yml
@@ -21,7 +21,7 @@ on:
       # バージョン形式のチェック有無
       check_on:
         description: 'Check validation input version'
-        default: on
+        default: 'on'
         required: true
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
@@ -41,6 +41,7 @@ jobs:
           echo "valid test version"
         else
           echo "invalid test version"
+          exit 1
         fi
 
     - name: Check Input Release Version
@@ -49,6 +50,7 @@ jobs:
         if echo "${{ github.event.inputs.release_version }}" | grep -E "^4\.[0-9]+\.[0-9]+$"; then
           echo "valid test version"
         else
+          echo "invalid test version"
           echo "invalid test version"
         fi
 
